In [ ]:
%matplotlib inline 
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt

In [ ]:
def initialization(file):
    data = pd.read_csv(file)
    rwdata  = np.array(data)
    train_set  = (((rwdata.T)[1:]).T)/255
    label_set = (rwdata.T)[0]
    return label_set , train_set
label_set , train_set = initialization("mnist_test.csv")
m = label_set.shape[0]
def oned_set(Y):
    one_hot_Y = np.zeros((Y.size, Y.max() + 1))
    one_hot_Y[np.arange(Y.size), Y] = 1
    return one_hot_Y.T


In [ ]:
def Activ(x):
    return np.maximum(x, 0)
def Activd(x):
    return x > 0

In [ ]:
def SoftMaxx(Z):
    A = np.exp(Z) / sum(np.exp(Z))
    return A

In [ ]:
def initial_conditions():
    w0 = np.random.rand(16, 784).astype(np.float64) - .5
    b0 = np.random.rand(16, 1).astype(np.float64)  - .5
    w1 = np.random.rand(10, 16).astype(np.float64) - .5
    b1 = np.random.rand(10, 1).astype(np.float64) - .5
    return w0, b0, w1, b1

In [ ]:
def forward_propagation(train_set, w0, b0, w1, b1):
    z0 = w0.dot(train_set) + b0  # 16xm
    a1 = Activ(z0) 
    z1 = w1.dot(a1) + b1 #10xm
    a2 = SoftMaxx(z1)
    return z0, a1, z1, a2

In [ ]:
def Costfun(a2, label_set):
    Y = oned_set(label_set)
    cost_ar = (a2 - Y)
    return cost_ar

In [ ]:
def back_propagation(z0, a1, z1, cost, train_set):
    dz1  = 2*cost
    dw1 = 1 / m *((dz1).dot(a1.T)) 
    db1 = 1 / m * (np.sum(dz1))
    dz0 = ((dz1.T).dot(w1)).T *Activd(z0)
    dw0 = 1 / m * (dz0).dot(train_set.T)
    db0 = 1 / m * np.sum(dz0)
    return dw0, db0, dw1, db1

In [ ]:
def updation(w0, b0, w1, b1, dw0, db0, dw1, db1, a):
    w0 = w0 - a*dw0
    w1 = w1 - a*dw1
    b0 = b0 - a*db0
    b1 = b1 - a*db1
    return w0, w1, b0, b1

In [ ]:
w0, b0, w1, b1, = initial_conditions()

In [ ]:
def get_accuracy(Y, pred):
    return np.sum(pred == Y) / Y.size * 100    

In [ ]:
def training(w0, b0, w1, b1, iterations, alpha):    
    label_set , train_set = initialization("mnist_train.csv")
    train_set = train_set.T
    for j in range(iterations): 
        z0, a1, z1, ou = forward_propagation(train_set, w0, b0, w1, b1)
        cost_ar = Costfun(ou, label_set)
        dw0, db0, dw1, db1 = back_propagation( z0, a1, z1, cost_ar, train_set)
        w0, w1, b0, b1 =  updation(w0, b0, w1, b1, dw0, db0, dw1, db1, alpha)
        pred_array = (np.argmax(ou, 0))
        if (j % 10 == 0):
            print("Iteration " , j)
            print(get_accuracy(label_set, pred_array))
            print(pred_array , label_set)
    return pred_array , w0, b0, w1, b1


In [ ]:
pred_array , w0, b0, w1, b1  = training(w0, b0, w1, b1, 401, 0.1)

Iteration  0
88.06813446890781
[0 4 1 ... 5 2 8] [0 4 1 ... 5 6 8]
Iteration  10
23.15871931198853
[0 7 5 ... 5 0 5] [0 4 1 ... 5 6 8]
Iteration  20
50.32917215286922
[0 4 4 ... 5 0 5] [0 4 1 ... 5 6 8]
Iteration  30
62.95604926748779
[0 4 1 ... 5 0 5] [0 4 1 ... 5 6 8]
Iteration  40
71.37452290871515
[0 4 1 ... 5 0 5] [0 4 1 ... 5 6 8]
Iteration  50
75.06958449307488
[0 4 1 ... 8 0 5] [0 4 1 ... 5 6 8]
Iteration  60
77.7462957715962
[0 4 1 ... 8 0 8] [0 4 1 ... 5 6 8]
Iteration  70
76.38960649344155
[0 4 1 ... 5 0 5] [0 4 1 ... 5 6 8]
Iteration  80
75.95459924332071
[0 4 1 ... 8 0 8] [0 4 1 ... 5 6 8]
Iteration  90
82.08303471724528
[0 4 1 ... 5 0 5] [0 4 1 ... 5 6 8]
Iteration  100
73.31788863147719
[0 4 1 ... 5 0 0] [0 4 1 ... 5 6 8]
Iteration  110
83.59472657877632
[0 4 1 ... 5 0 5] [0 4 1 ... 5 6 8]
Iteration  120
81.20135335588927
[0 4 1 ... 5 0 5] [0 4 1 ... 5 6 8]
Iteration  130
86.47477457957633
[0 4 1 ... 5 0 8] [0 4 1 ... 5 6 8]
Iteration  140
81.46635777262954
[0 4 1 ... 5 